### ISSUE TITLE
Mod not loading correctly

### ISSUE THREAD

**Issue by Humza2205** [henkelmax/ultimate-car-mod#103]
**Bug description**
The mod did not load correctly: Failure message: "Ultimate Car Mod (car) encountered an error during the common_setup event phase"
		java.lang.NullPointerException: Registry Object not present: car:canola_seeds

**Expected behavior**
i expected the mod to load correctly with no issue since i ahd used the mod for 1.18.2 previously

**crash report**
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-07-31 12:45:56
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.1-42.0.1-universal.jar%23171!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.1-42.0.1-universal.jar%23171!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:582) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:576) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:697) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.1-20220727.212338-srg.jar%23166!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.1-42.0.1.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
-- MOD car --
Details:
	Mod File: /C:/Users/humze/curseforge/minecraft/Instances/hello 4/mods/car-1.19.1-1.0.0.jar
	Failure message: Ultimate Car Mod (car) encountered an error during the common_setup event phase
		java.lang.NullPointerException: Registry Object not present: car:canola_seeds
	Mod Version: 1.19.1-1.0.0
	Mod Issue URL: https://github.com/henkelmax/ultimate-car-mod/issues
	Exception message: java.lang.NullPointerException: Registry Object not present: car:canola_seeds
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.1-42.0.1-universal.jar%23171!/:?] {re:mixin,re:classloading}
	at de.maxhenkel.car.Main.commonSetup(Main.java:176) ~[car-1.19.1-1.0.0.jar%23145!/:1.19.1-1.0.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.1-42.0.1.jar%23168!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.1-42.0.1.jar%23167!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 521868288 bytes (497 MiB) / 922746880 bytes (880 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.12015.1008
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18346.02
	Virtual memory used (MB): 10467.05
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 990.67
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.1-20220727.212338-srg.jar             |Minecraft                     |minecraft                     |1.19.1              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		configured-1.5.6-1.19.jar                         |Configured                    |configured                    |1.5.6               |SIDED_SETU|Manifest: NOSIGNATURE
		landmines-1.0.4b-forge-mc1.19.jar                 |Landmines                     |landmines                     |1.0.4b              |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar  |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6b              |SIDED_SETU|Manifest: NOSIGNATURE
		burgermod-2.9.0-1.19.1.jar                        |Burger Mod                    |burgermod                     |2.9.0               |SIDED_SETU|Manifest: NOSIGNATURE
		rechiseled-1.0.10c-forge-mc1.19.jar               |Rechiseled                    |rechiseled                    |1.0.10c             |SIDED_SETU|Manifest: NOSIGNATURE
		simpleplanes-1.19-4.14.2.jar                      |Simple Planes                 |simpleplanes                  |1.19-4.14.2         |SIDED_SETU|Manifest: NOSIGNATURE
		portabletanks-1.1.5a-forge-mc1.19.jar             |portabletanks                 |portabletanks                 |1.1.5a              |SIDED_SETU|Manifest: NOSIGNATURE
		wormhole-1.1.10b-forge-mc1.19.jar                 |Wormhole (Portals)            |wormhole                      |1.1.10b             |SIDED_SETU|Manifest: NOSIGNATURE
		simplemagnets-1.1.8b-forge-mc1.19.jar             |Simple Magnets                |simplemagnets                 |1.1.8b              |SIDED_SETU|Manifest: NOSIGNATURE
		connectedglass-1.1.4b-forge-mc1.19.jar            |Connected Glass               |connectedglass                |1.1.4b              |SIDED_SETU|Manifest: NOSIGNATURE
		additionallanterns-1.0.1a-forge-mc1.19.jar        |Additional Lanterns           |additionallanterns            |1.0.1a              |SIDED_SETU|Manifest: NOSIGNATURE
		propellerhats-1.19-1.0.1.jar                      |Propeller Hats                |propellerhats                 |1.19-1.0.1          |SIDED_SETU|Manifest: NOSIGNATURE
		wirelesschargers-1.0.6b-forge-mc1.19.jar          |Wireless Chargers             |wirelesschargers              |1.0.6b              |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |SIDED_SETU|Manifest: NOSIGNATURE
		PuzzlesLib-v4.1.2-1.19.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.1.2               |SIDED_SETU|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		movingelevators-1.3.9-forge-mc1.19.jar            |Moving Elevators              |movingelevators               |1.3.9               |SIDED_SETU|Manifest: NOSIGNATURE
		trashcans-1.0.15a-forge-mc1.19.jar                |Trash Cans                    |trashcans                     |1.0.15a             |SIDED_SETU|Manifest: NOSIGNATURE
		tesseract-1.0.27b-forge-mc1.19.jar                |Tesseract                     |tesseract                     |1.0.27b             |SIDED_SETU|Manifest: NOSIGNATURE
		ObsidianBoat-1.10.0-build.19+mc1.19.1.jar         |Obsidian Boat                 |obsidianboat                  |1.10.0-build.19+mc1.|SIDED_SETU|Manifest: NOSIGNATURE
		car-1.19.1-1.0.0.jar                              |Ultimate Car Mod              |car                           |1.19.1-1.0.0        |ERROR     |Manifest: NOSIGNATURE
		forge-1.19.1-42.0.1-universal.jar                 |Forge                         |forge                         |42.0.1              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Xaeros_Minimap_22.13.0_Forge_1.19.1.jar           |Xaero's Minimap               |xaerominimap                  |22.13.0             |SIDED_SETU|Manifest: NOSIGNATURE
		itemcollectors-1.1.5b-forge-mc1.19.jar            |Item Collectors               |itemcollectors                |1.1.5b              |SIDED_SETU|Manifest: NOSIGNATURE
		XaerosWorldMap_1.26.2_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.26.2              |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 4b26363f-c5ea-4261-902a-47b42278b3de
	FML: 42.0
	Forge: net.minecraftforge:42.0.1

**Versions**
- 1.19.1
- Forge version 42.0.1
- Mod version car-1.19.1-1.0.0.jar

**Other mods**

SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.0.19-forge-mc1.19.jar

Tesseract
SuperMartijn642
tesseract-1.0.27b-forge-mc1.19.jar

TheObsidianBoat
UnRealDinnerbone
ObsidianBoat-1.10.0-build.19+mc1.19.1.jar

Trash Cans
SuperMartijn642
trashcans-1.0.15a-forge-mc1.19.jar

Ultimate Car Mod
henkelmax
car-1.19.1-1.0.0.jar

Wireless Chargers
SuperMartijn642
wirelesschargers-1.0.6b-forge-mc1.19.jar

Wormhole (Portals)
SuperMartijn642
wormhole-1.1.10b-forge-mc1.19.jar

Xaero's Minimap
xaero96
Xaeros_Minimap_22.13.0_Forge_1.19.1.jar

Xaero's World Map
xaero96
XaerosWorldMap_1.26.2_Forge_1.19.1.jar

**Comment by henkelmax** [comment]
Please don't post the plain crash report to the issue. This was stated in the bug template. Please send the full logs as a github gist.

**Comment by henkelmax** [comment]
I'm also not able to reproduce this issue without other mods. Can you please check which mod in combination with the car mod causes the issue?

**Comment by North-West-Wind** [comment]
I also have this problem, and I suspect Roughly Enough Resources is the reason. The game started normally with RER removed.

**Comment by henkelmax** [comment]
Closed due to inactivity
