### ISSUE TITLE
Can't construct cars

### ISSUE THREAD

**Issue by Sniperczz** [henkelmax/ultimate-car-mod#113]
When i try to build a car, it doesn't spawn

1. Place a cabin in the first slot
2. Place four wheels in the next four slots
3. Place an engine in the sixth slot
4. Place a tank in the seventh slot
5. Click spawn
6. Doesn't work

I was expecting to spawn a car.

java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "retVal" is null
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:687) ~[OptiFine-1.19_HD_U_H9_pre4.jar%23154!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$onCharEvent$5(KeyboardHandler.java:662) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.KeyboardHandler.m_90889_(KeyboardHandler.java:647) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$9(KeyboardHandler.java:711) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$setupCallbacks$10(KeyboardHandler.java:710) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23128!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23136!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:448) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23148!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.110.jar%2393!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[20:45:05] [Render thread/INFO]: [CHAT] Install the "Configured" mod to access the in-game config
[20:46:10] [Server thread/INFO]: Saving and pausing game...
[20:46:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:overworld
[20:46:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_nether
[20:46:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_end
[20:46:18] [Render thread/ERROR]: ########## GL ERROR ##########
[20:46:18] [Render thread/ERROR]: @ Render
[20:46:18] [Render thread/ERROR]: 65540: Invalid scancode -1
[20:49:03] [Server thread/INFO]: [Sniperczzzz: Set own game mode to Survival Mode]
[20:49:18] [Server thread/INFO]: Saving and pausing game...
[20:49:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:overworld
[20:49:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_nether
[20:49:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_end
[20:53:47] [Server thread/INFO]: Saving and pausing game...
[20:53:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:overworld
[20:53:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_nether
[20:53:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_end
[21:01:38] [Server thread/INFO]: Saving and pausing game...
[21:01:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:overworld
[21:01:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_nether
[21:01:38] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_end
[21:38:36] [Server thread/INFO]: Saving and pausing game...
[21:38:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:overworld
[21:38:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_nether
[21:38:36] [Server thread/INFO]: Saving chunks for level 'ServerLevel[City]'/minecraft:the_end
[21:38:38] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[21:38:38] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[21:38:38] [Render thread/INFO]: Stopping JEI
[21:38:38] [Server thread/INFO]: Sniperczzzz lost connection: Disconnected
[21:38:38] [Server thread/INFO]: Sniperczzzz left the game

- 1.19 (forge optifine)
- 41.0.110
- 1.19-1.0.10

Just Enough Items

https://user-images.githubusercontent.com/113470079/190168629-62f13d4b-68a0-44ed-a9f1-94a8e301a812.mp4

**Comment by henkelmax** [comment]
Please don't post logs in plain text. Use github gist like described in the template.

**Comment by henkelmax** [comment]
Closed due to inactivity.
