### ISSUE TITLE
GAME CRASH

### ISSUE THREAD

**Issue by BRuhplay69** [henkelmax/ultimate-car-mod#2]
Almost everything I right click on crashes my game like the gas station, the blast furnace, the generator, the oil mill, etc.
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/28/20 10:35 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidUtil.getFluidContained(Lnet/minecraft/item/ItemStack;)Lnet/minecraftforge/common/util/LazyOptional;
	at de.maxhenkel.car.corelib.fluid.FluidUtils.tryFluidInteraction(FluidUtils.java:141) ~[?:1.16.2-1.0.2] {re:classloading}
	at de.maxhenkel.car.blocks.BlockBlastFurnace.func_225533_a_(BlockBlastFurnace.java:30) ~[?:1.16.2-1.0.2] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:634) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:288) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1438) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:931) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:585) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.22.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/1574573264.call(Unknown Source) [forge-1.16.2-33.0.22.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.maxhenkel.car.corelib.fluid.FluidUtils.tryFluidInteraction(FluidUtils.java:141)
	at de.maxhenkel.car.blocks.BlockBlastFurnace.func_225533_a_(BlockBlastFurnace.java:30)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:634)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:288)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1344)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1596)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['RythmStylz'/13104, l='ClientLevel', x=3313.25, y=65.00, z=-3226.06]]
	Chunk stats: Client Chunk Cache: 289, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (-22,63,-173), Chunk: (at 10,3,3 in -2,-11; contains blocks -32,0,-176 to -17,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2709640 game time, 3080388 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1975)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:606)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/1574573264.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 786256200 bytes (749 MB) / 2382364672 bytes (2272 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.22.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.22
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.22-client.jar Minecraft {minecraft@1.16.2 DONE}
		Trash-Cans-Mod-1.16.2.jar Trash Cans {trashcans@1.0.2 DONE}
		car-1.16.2-1.0.2.jar Ultimate Car Mod {car@1.16.2-1.0.2 DONE}
		forge-1.16.2-33.0.22-universal.jar Forge {forge@33.0.22 DONE}
		Scuba-Gear-Mod-1.16.2.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		Simple-Planes-Mod-1.16.2.jar Simple Planes {simpleplanes@1.16.2-2.0.5.3 DONE}
		Pams-HarvestCraft-2-Food-Core-Mod-1.16.2.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		Lumberjack-Mod-1.16.2.jar LumberJack {lumberjack@2.1.3 DONE}
		Additional-Lights-Mod-1.16.2.jar Additional Lights {additional_lights@2.1.1 DONE}
		Corpse-Mod-1.16.2.jar Corpse {corpse@1.16.2-1.0.7 DONE}
		jei-1.16.2-7.1.3.20.jar Just Enough Items {jei@7.1.3.20 DONE}
	Launched Version: 1.16.2-forge-33.0.22
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13571 Compatibility Profile Context 19.9.3 26.20.13025.1004, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by henkelmax** [comment]
Thank you for reporting this issue. I found the cause of the crashes.
But please use the precreated bug issue template next time.

**Comment by BRuhplay69** [comment]
Hey Max Im sorry that i didnt put it on the bug issue template that was my
first time on the website because i just wanted to let you guys know

**Comment by henkelmax** [comment]
It's fine, just wanted to tell you for the next time.
