### ISSUE TITLE
Bio-Diesel source block crashes the game and renders the world file unusable when you break a block/grab it via bucket

### ISSUE THREAD

**Issue by BurritoLad** [henkelmax/ultimate-car-mod#57]
**Bug description**
I was messing with the mod when I misplaced a Bio-Diesel bucket, it landing on the Tank I was filling. I attempted to scoop it up with an empty bucket, when my game crashed with the following error:

> Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_6718_(net.minecraft.world.level.LevelReader)" because "this.f_54689_" is null

Upon attempting to reload the world, Minecraft hung after completing the world reload. I had to exit it out via Task Manager. This bug repeated when I did the same thing, but instead broke the Tank it was on top of.

**Steps to reproduce the issue**
1. Place Bio-Deisel Bucket on ground
2. Grab Bio-Deisel on ground with bucket
3. Game _should_ crash
4. Reload world
5. Minecraft _should_ hang on 100%

**Expected behavior**
I expected the Bio-Diesel to be scooped into the water bucket, and also expected the world to load normally.

**Log files**
Heres the stacktrace in the render thread.
```
	at net.minecraft.world.level.block.LiquidBlock.m_7417_(LiquidBlock.java:117) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60728_(BlockBehaviour.java:669) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60705_(BlockBehaviour.java:610) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading}
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:246) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_6933_(Level.java:213) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_7731_(Level.java:177) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:192) ~[forge-1.17.1-37.0.25-universal.jar%2364!:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:133) ~[forge-1.17.1-37.0.25-universal.jar%2364!:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105267_(MultiPlayerGameMode.java:121) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105269_(MultiPlayerGameMode.java:143) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91276_(Minecraft.java:1498) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1825) ~[client-1.17.1-20210706.113038-srg.jar%2360!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
```

**Versions**
1.17.1
Forge for 1.17.1 37.0.25
Ultimate Car Mod 1.17.1-1.0.1

**Other mods**
[Collective](https://www.curseforge.com/minecraft/mc-mods/collective/), [Villager Names](https://www.curseforge.com/minecraft/mc-mods/villager-names), [Corpse](https://www.curseforge.com/minecraft/mc-mods/corpse), [More Villagers](https://www.curseforge.com/minecraft/mc-mods/more-villagers)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/78869406/128548711-f08dd56d-2277-482d-88ec-46a3777e2d54.png)

**Comment by henkelmax** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/7922

**Comment by BurritoLad** [comment]
Ah, glad to see I'm not the only one having these problems.
