### ISSUE TITLE
crashing when adding canola to mill and clicking on it after. same with blast furnace

### ISSUE THREAD

**Issue by thomasFir** [henkelmax/ultimate-car-mod#66]
**Please read the [FAQ](https://modrepo.de/minecraft/car/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. Go to load game
2. Click on canola mill, blast furnace after you add materials and energize
3. Scroll down to '...'

**Expected behavior**
game will crash when you add canola or wood to the furnace and activate them. have tried in creative and not. if i delete the block and replace it i can open in again until i try and use it. game saves and crashes every time

**Log files**
---- Minecraft Crash Report ----
// My bad.

Time: 9/24/21, 8:36 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.lazyParentSupplier" is null
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:93) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:188) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.fluids.FluidUtil.getFluidHandler(FluidUtil.java:434) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading}
	at de.maxhenkel.car.corelib.fluid.FluidUtils.tryFluidInteraction(FluidUtils.java:148) ~[car-1.17.1-1.0.9.jar%2353!:1.17.1-1.0.9] {re:classloading}
	at de.maxhenkel.car.blocks.BlockOilMill.m_6227_(BlockOilMill.java:38) ~[car-1.17.1-1.0.9.jar%2353!:1.17.1-1.0.9] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:653) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1552) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1828) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1646) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1014) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.69.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapabilities(CapabilityProvider.java:93) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.getCapability(CapabilityProvider.java:188) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.ICapabilityProvider.getCapability(ICapabilityProvider.java:48) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading,re:mixin}
	at net.minecraftforge.fluids.FluidUtil.getFluidHandler(FluidUtil.java:434) ~[forge-1.17.1-37.0.69-universal.jar%2360!:?] {re:classloading}
	at de.maxhenkel.car.corelib.fluid.FluidUtils.tryFluidInteraction(FluidUtils.java:148) ~[car-1.17.1-1.0.9.jar%2353!:1.17.1-1.0.9] {re:classloading}
	at de.maxhenkel.car.blocks.BlockOilMill.m_6227_(BlockOilMill.java:38) ~[car-1.17.1-1.0.9.jar%2353!:1.17.1-1.0.9] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:653) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1552) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1828) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['ThomasFir'/141, l='ClientLevel', x=835.97, y=65.00, z=-386.17]]
	Chunk stats: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,72,-48), Section: (at 0,8,0 in 9,4,-3; chunk contains blocks 144,0,-48 to 159,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 366767 game time, 263016 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2244) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:681) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.69.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1102883440 bytes (1051 MiB) / 2262827008 bytes (2158 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A8-5600K APU with Radeon(tm) HD Graphics   
	Identifier: AuthenticAMD Family 21 Model 16 Stepping 1
	Microarchitecture: Piledriver
	Frequency (GHz): 4.30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.12033.1007
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 15940.62
	Virtual memory used (MB): 10181.18
	Swap memory total (MB): 3712.00
	Swap memory used (MB): 143.86
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Launched Version: forge-37.0.69
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Radeon RX 570 Series GL version 3.2.14736 Core Profile Forward-Compatible Context 20.10.1 27.20.12033.1007, ATI Technologies Inc.
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A8-5600K APU with Radeon(tm) HD Graphics 
	Player Count: 1 / 8; [ServerPlayer['ThomasFir'/141, l='ServerLevel[epic city]', x=835.95, y=65.00, z=-386.18]]
	Data Packs: vanilla, mod:car (incompatible), mod:forge, mod:jei, mod:journeymap (incompatible)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		car-1.17.1-1.0.9.jar                              |Ultimate Car Mod              |car                           |1.17.1-1.0.9        |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.69-universal.jar                |Forge                         |forge                         |37.0.69             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		journeymap-1.17.1-5.7.3rc3.jar                    |Journeymap                    |journeymap                    |5.7.3rc3            |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.0.0.16.jar                           |Just Enough Items             |jei                           |8.0.0.16            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3708eafd-f929-4adb-a2bd-d64a0d7f1f2f
	FML: 37.0
	Forge: net.minecraftforge:37.0.69

**Comment by henkelmax** [comment]
I can't reproduce your issue at all.

![image](https://user-images.githubusercontent.com/13237524/134762741-485468b0-06f8-4423-8bd5-13e7d618289d.png)

![image](https://user-images.githubusercontent.com/13237524/134762749-2b07fbc1-fac3-4d5e-9fa5-5cebb96376f5.png)

Please fill out the bug report template properly and fill out all information that is needed. Please also post your logs with github gist.
